add SQL schema
wakokasabuta/InstantStudy pull request #3
Opened 2024-06-26 04:15 UTC by wakokasabuta

2024-06-26 15:54 UTC, 4rgc requested changes
いいね、エラーは消えた！
ただschemaには問題が多い、、
説明が足りなかっら言って！

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +  PRIMARY KEY (`user_id`),
Post の Primary Key が `user_id` になってる

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +  `following_id` INT NOT NULL)
どっちもForeign Keyが付いてないとユーザに連携（？）できない

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +  `following_id` INT NOT NULL)
あとはprimary keyがない
ここはこの二つのコラムをcomposite primary key にすることが必要
それぞれがユニークな値ではないから

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +CREATE TABLE IF NOT EXISTS `projectx`.`comments` (
Primary keyがない

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +  CONSTRAINT `posts_fk`
foreign keyの名前だけど本テーブルの名前を入れても何の機能があるか分からないから`user_id_fk`とかの方がいいかも

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +  CONSTRAINT `commnets_fk`
ここもFKの名前を直して

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +    FOREIGN KEY (`id`)
`user`テーブルの`id`に繋ぐのは`posts`の`user_id`に繋ぐんじゃ？

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +    FOREIGN KEY (`id`)
ここも：
`user`テーブルの`id`に繋ぐのは`comments`の`user_id`に繋ぐんじゃ？

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +  `post_id` INT NOT NULL,
`post_id`を`posts`テーブルに繋ぐforeign key がない

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +  CONSTRAINT `media_fk`
ここも：foreign keyの名前

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +    FOREIGN KEY (`id`)
メディアをユーザーに繋ぐ必要ある？
メディアはpost_idがあるからpostsに繋ぐんじゃ？

2024-06-26 15:54 UTC, 4rgc commented on prjctx.sql
> +  `post_id` INT NOT NULL)
ここも：foreign key がない、同じくcomposite primary keyが必要

2024-06-27 15:15 UTC, wakokasabuta commented on prjctx.sql
> +  `following_id` INT NOT NULL)
ここのcomposite primary keyの意味が分からん

2024-06-27 15:15 UTC, wakokasabuta commented on prjctx.sql
> +  `post_id` INT NOT NULL)
ここも上に同じく意味が分からん

2024-07-01 19:12 UTC, 4rgc requested changes

2024-07-01 19:12 UTC, 4rgc commented on prjctx.sql
> +  `creation_date` VARCHAR(20) NULL,
ここは`DATETIME`タイプの方が合ってるね

2024-07-01 19:12 UTC, 4rgc commented on prjctx.sql
> +  `creation_data` VARCHAR(45) NOT NULL,
同じく、`DATETIME`にした方がいい
あと`creation_date`ね

2024-07-01 19:12 UTC, 4rgc commented on prjctx.sql
> +    ON UPDATE NO ACTION,
これ間違ってない？

2024-07-02 15:30 UTC, wakokasabuta commented on prjctx.sql
> +    ON UPDATE NO ACTION,
どういう風に間違えてる？

2024-07-03 02:14 UTC, 4rgc approved these changes
LGTM!

2024-07-03 15:24 UTC, merged